### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by Andbaz1** [lxrootard/eufy#2]
Plugin Eufy dernière version installé sur Jeedom PI4 bullseye j'ai ce message qui se répète sans cesse :
"thrown in /var/www/html/plugins/eufy/core/class/eufy.class.php on line 258
0035|[Sun Jun 16 20:22:24.899734 2024] [php7:error] [pid 1149523] [client 127.0.0.1:40020] PHP Fatal error:  Uncaught Error: Call to a member function getGeneric_type() on bool in /var/www/html/plugins/eufy/core/class/eufy.class.php:258"

**Comment by lxrootard** [comment]
bug fixé dans release v2.5
